class_name SpriteSheet
extends Resource
## Horizontal strip of animation frames, generated by tools/sprites/bake_sprites.gd.
## Each animation is a run of consecutive cells. Pure data + one draw helper.

## Used when an animation is missing (every sheet has at least "walk").
const FALLBACK := &"walk"

@export var texture: Texture2D
@export var cell_size := Vector2i(1, 1)
## Animation name -> Vector3i(first cell, frame count, frames per second).
@export var animations: Dictionary[StringName, Vector3i] = {}


func has_animation(anim: StringName) -> bool:
	return animations.has(anim)


## Absolute cell index of `anim` after `time` seconds (looping).
func frame_at(anim: StringName, time: float) -> int:
	var info: Vector3i = animations.get(anim, animations.get(FALLBACK, Vector3i(0, 1, 1)))
	var count := maxi(info.y, 1)
	return info.x + posmod(int(floor(time * info.z)), count)


func region(frame: int) -> Rect2:
	return Rect2(frame * cell_size.x, 0, cell_size.x, cell_size.y)


## Draws `frame` scaled to `height` px, feet at `foot_y`, mirrored when facing < 0.
func draw(canvas: CanvasItem, frame: int, height: float, foot_y: float, facing: float, tint: Color) -> void:
	var size := Vector2(height * cell_size.x / float(cell_size.y), height)
	canvas.draw_set_transform(Vector2.ZERO, 0.0, Vector2(facing, 1.0))
	canvas.draw_texture_rect_region(texture, Rect2(Vector2(-size.x * 0.5, foot_y - size.y), size),
		region(frame), tint)
	canvas.draw_set_transform(Vector2.ZERO)
